/**
 * services/appointments.ts — Appointments service backed by Supabase.
 *
 * All functions return { data, error } matching the ServiceResult<T> pattern.
 * RLS on the `appointments` table ensures each user only sees their own rows.
 */

import { supabase } from '../lib/supabase';
import { Appointment, AppointmentStatus } from '../lib/mockData';
import { ServiceResult } from './auth';

// ─── DB-level types ───────────────────────────────────────────────────────────

/** Shape of a row in the Supabase `appointments` table. */
export interface DbAppointment {
  id: string;
  user_id: string;
  client_name: string;
  client_phone: string;
  /** The first / primary selected service — used for display and slot duration lookups. */
  primary_service_id: string;
  /** All selected service IDs stored as a Postgres TEXT[] array. */
  service_ids: string[];
  date: string;           // 'yyyy-MM-dd'
  time: string;           // 'HH:mm'
  total_duration: number; // sum of all selected service durations
  total_price: number;    // sum of all selected service prices
  status: AppointmentStatus;
  created_at: string;     // ISO timestamp
}

/** Payload for inserting a new row — id and created_at are generated by the DB. */
export type NewDbAppointment = Omit<DbAppointment, 'id' | 'created_at'>;

// ─── Mapper ───────────────────────────────────────────────────────────────────

/** Maps a DB row to the Appointment shape used throughout the UI. */
function dbToAppointment(db: DbAppointment): Appointment {
  return {
    id: db.id,
    clientName: db.client_name,
    clientPhone: db.client_phone,
    serviceId: db.primary_service_id,
    serviceIds: db.service_ids,
    date: db.date,
    time: db.time,
    status: db.status,
    totalDuration: db.total_duration,
    totalPrice: db.total_price,
    createdAt: db.created_at,
  };
}

// ─── Functions ───────────────────────────────────────────────────────────────

/**
 * Fetch all appointments for the currently authenticated user,
 * ordered by date and time ascending.
 */
export async function fetchAppointments(): Promise<ServiceResult<Appointment[]>> {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { data: null, error: 'Not authenticated.' };

  const { data, error } = await supabase
    .from('appointments')
    .select('*')
    .eq('user_id', user.id)
    .order('date', { ascending: true })
    .order('time', { ascending: true });

  if (error) return { data: null, error: error.message };
  return { data: (data as DbAppointment[]).map(dbToAppointment), error: null };
}

/**
 * Create a new appointment row.
 * Returns the created appointment with its server-assigned id and created_at.
 */
export async function createAppointment(
  payload: NewDbAppointment,
): Promise<ServiceResult<Appointment>> {
  const { data, error } = await supabase
    .from('appointments')
    .insert(payload)
    .select()
    .single();

  if (error) return { data: null, error: error.message };
  return { data: dbToAppointment(data as DbAppointment), error: null };
}

/**
 * Update the status of an existing appointment.
 * RLS ensures a user can only update their own rows.
 */
export async function updateAppointmentStatus(
  id: string,
  status: AppointmentStatus,
): Promise<ServiceResult<{ id: string; status: AppointmentStatus }>> {
  const { error } = await supabase
    .from('appointments')
    .update({ status })
    .eq('id', id);

  if (error) return { data: null, error: error.message };
  return { data: { id, status }, error: null };
}

/**
 * Cancel an appointment — convenience wrapper around updateAppointmentStatus.
 */
export async function cancelAppointment(
  id: string,
): Promise<ServiceResult<{ id: string }>> {
  const result = await updateAppointmentStatus(id, 'cancelled');
  if (result.error) return { data: null, error: result.error };
  return { data: { id }, error: null };
}
